### ISSUE TITLE
Things to do

### ISSUE THREAD

**Issue by SeanRich18** [SeanRich18/Citrix_Log_Phraser#5]
- [x] Capture new data
- [ ] Caluate duration based on login & Logoff time
- [x] Modify duplication methos to account for larger logs
- [ ] Add time stamp to duplication (Logoff)
- [x] Add method for calculating duration
- [x] Date will become new priority for if duplication occures
- [x] Add method for updating the vector entries with time and duration

The idea here is to start leaving things in a bigger logs.  When the program runs against the log I will be able to rename the log to something else and let the script just create a new one.  I will toss the date into the Log name to make it unique.  There for we have archiving.

**Comment by Fuzzylr** [comment]
Over the last couple of days I have spent a lot of time working on building upon the orginial program.  To my success I have managed to complete these items while maintaining what I hope to be very little memory leaks.

**Comment by Fuzzylr** [comment]
Tomorrow I will do some testing at work to see how well things worked out with this new code.  Hopefully this will bring things to a conclusion.

**Comment by SeanRich18** [comment]
Most of these items have been completed.  Version 3.0 will be next to be produced.
